### ISSUE TITLE
Error after run 

### ISSUE THREAD

**Issue by aqueezer** [bahmutov/cypress-select-tests#170]
Everything in my project was set like in the description.
I installed: **npm install --save-dev cypress-select-tests**
and added:

```
const selectTestsWithGrep = require ('cypress-select-tests / grep')
module.exports = (on, config) => {
  on ('file: preprocessor', selectTestsWithGrep (config))
}
```
to **plugins / index.js**

also I'd added keywords to test description.

I run the tests: npx cypress run --env grep = "Smoke" and it get:

`        Just tests tagged with: Smoke

The following error was thrown by a plugin. We stopped running your tests because a plugin crashed. Please check your plugins file (`/home/adam/automaty/Zerce/cypress/plugins/index.js`)

 SyntaxError: Unexpected token (2:10)
    at Parser.pp$4.raise (/home/adam/automaty/Zerce/node_modules/falafel/node_modules/acorn/dist/acorn.js:2927:15)
    at Parser.pp.unexpected (/home/adam/automaty/Zerce/node_modules/falafel/node_modules/acorn/dist/acorn.js:698:10)
    at Parser.pp.semicolon (/home/adam/automaty/Zerce/node_modules/falafel/node_modules/acorn/dist/acorn.js:675:66)
    at Parser.pp$1.parseExpressionStatement (/home/adam/automaty/Zerce/node_modules/falafel/node_modules/acorn/dist/acorn.js:1154:10)
    at Parser.pp$1.parseStatement (/home/adam/automaty/Zerce/node_modules/falafel/node_modules/acorn/dist/acorn.js:889:26)
    at Parser.pp$1.parseBlock (/home/adam/automaty/Zerce/node_modules/falafel/node_modules/acorn/dist/acorn.js:1170:23)
    at Parser.pp$1.parseStatement (/home/adam/automaty/Zerce/node_modules/falafel/node_modules/acorn/dist/acorn.js:854:36)
    at Parser.pp$1.parseTopLevel (/home/adam/automaty/Zerce/node_modules/falafel/node_modules/acorn/dist/acorn.js:755:23)
    at Parser.parse (/home/adam/automaty/Zerce/node_modules/falafel/node_modules/acorn/dist/acorn.js:555:17)
    at Function.parse (/home/adam/automaty/Zerce/node_modules/falafel/node_modules/acorn/dist/acorn.js:578:37)
    at Object.parse (/home/adam/automaty/Zerce/node_modules/falafel/node_modules/acorn/dist/acorn.js:5143:19)
    at module.exports (/home/adam/automaty/Zerce/node_modules/falafel/index.js:23:22)
    at Object.findTests (/home/adam/automaty/Zerce/node_modules/cypress-select-tests/src/spec-parser.js:95:3)
    at process (/home/adam/automaty/Zerce/node_modules/cypress-select-tests/src/itify.js:18:33)
    at Stream.onend (/home/adam/automaty/Zerce/node_modules/cypress-select-tests/src/itify.js:52:18)
    at _end (/home/adam/automaty/Vapk/node_modules/through/index.js:65:9)
    at Stream.stream.end (/home/adam/automaty/Zerce/node_modules/through/index.js:74:5)
    at DestroyableTransform.onend (/home/adam/automaty/Vapk/node_modules/@cypress/browserify-preprocessor/node_modules/readable-stream/lib/_stream_readable.js:577:10)
    at Object.onceWrapper (events.js:416:28)
    at DestroyableTransform.emit (events.js:322:22)
    at endReadableNT (/home/adam/automaty/Zerce/node_modules/@cypress/browserify-preprocessor/node_modules/readable-stream/lib/_stream_readable.js:1010:12)
    at processTicksAndRejections (internal/process/task_queues.js:84:21)
`

Anyone can help : ( ?

**Comment by ApplePP** [comment]
Got same error, @aqueezer have you fixed this?

**Comment by midleman** [comment]
Ditto. Same problem.
